- .eslintrc
- package.json
- test/rules/no-disabled-tests.js
- test/rules/no-focused-tests.js
- test/rules/no-spec-dupes.js
- test/rules/no-suite-dupes.js
Update to eslint ^1.1.0
Closes #12
> chore: update to the latest major version of eslint

- package.json
Closes #38, closes #39, closes #42, closes #45, closes #47.
> chore: bump ESLint

- .vimrc
- README.md
- docs/rules/no-assign-spyon.md
- index.js
- lib/rules/no-assign-spyon.js
- test/rules/no-assign-spyon.js
> feat(no-assign-spyon): add no-assign-spyon rule

- README.md
- docs/rules/no-global-setup.md
- index.js
- lib/rules/no-global-setup.js
- test/rules/no-global-setup.js
> feat(no-global-setup): add no-global-setup rule

- docs/rules/valid-expect.md
- lib/rules/valid-expect.js
- test/rules/valid-expect.js
> fix(valid-expect) check if matcher was called

- docs/rules/new-line-between-declarations.md
- index.js
- lib/rules/new-line-between-declarations.js
- test/rules/new-line-between-declarations.js
This is new optional rule.  Looking forward to your  feedback!
> feat: new line between declarations

- README.md
Hey, thanks for reviewing my PRs :) One more thing I missed for Readme - adding  link to the doc for the new rule. Hope this is the last fix for that change.
> fix: add link to docs

- docs/rules/no-unsafe-spy.md
- lib/rules/no-unsafe-spy.js
- test/rules/no-unsafe-spy.js
> no-safe-spy tracking createSpyObj

- README.md
- docs/rules/new-line-before-expect.md
- index.js
- lib/helpers/hasPaddingBetweenTokens.js
- lib/helpers/isPaddingBetweenTokens.js
- lib/rules/new-line-before-expect.js
- lib/rules/new-line-between-declarations.js
- test/rules/new-line-before-expect.js
- test/rules/new-line-between-declarations.js
> feat: new line before expect

- lib/rules/new-line-before-expect.js
- test/rules/new-line-before-expect.js
> simplified new-line-before-expect rule logic

- README.md
- docs/rules/prefer-jasmine-matcher.md
- index.js
- lib/rules/prefer-jasmine-matcher.js
- test/rules/prefer-jasmine-matcher.js
As per suggestion form the issue #35
> feat: prefer jasmine matcher

- docs/rules/prefer-jasmine-matcher.md
- index.js
- lib/rules/new-line-before-expect.js
- lib/rules/new-line-between-declarations.js
- test/rules/new-line-before-expect.js
- test/rules/new-line-between-declarations.js
Adding auto fixers for new-line-before-expect and new-line-between-declarations.
> Auto fixers for 2 rules

- README.md
- docs/rules/prefer-toHaveBeenCalledWith.md
- index.js
- lib/rules/prefer-toHaveBeenCalledWith.js
- test/rules/prefer-toHaveBeenCalledWith.js
> New prefer-toHaveBeenCalledWith rule

- lib/rules/prefer-jasmine-matcher.js
- test/rules/prefer-jasmine-matcher.js
> fix: error thrown on expect()

- lib/rules/no-suite-callback-args.js
- test/rules/no-suite-callback-args.js
> fix: supporting arrow functions

- docs/rules/new-line-before-expect.md
- lib/rules/new-line-before-expect.js
- test/rules/new-line-before-expect.js
> fix(new-line-before-expect): ok if another expect on the prev line

- lib/helpers/getName.js
- lib/rules/no-global-setup.js
- test/rules/no-global-setup.js
> fix(no-global-setup): incorrectly triggered by describe.only

- README.md
- docs/rules/expect-matcher.md
- docs/rules/expect-single-argument.md
- docs/rules/valid-expect.md
- index.js
- lib/rules/expect-matcher.js
- lib/rules/expect-single-argument.js
- lib/rules/valid-expect.js
- test/rules/expect-matcher.js
- test/rules/expect-single-argument.js
- test/rules/valid-expect.js
deprecating valid-expect.
closes #144
> feat: new expect-matcher and expect-single-argument rules.

- README.md
@burabure , thanks for quick review for my prev PR. Here is quick readme fix.
Thanks!
> fix: readme links fix

- docs/rules/expect-single-argument.md
- docs/rules/no-assign-spyon.md
- docs/rules/no-global-setup.md
- docs/rules/no-suite-callback-args.md
- docs/rules/no-unsafe-spy.md
- docs/rules/prefer-jasmine-matcher.md
Before submitting a pull request please make sure your commit message follows
[Angular commit conventions](https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md)
That way, when it's merged, [semantic-release](https://github.com/semantic-release/semantic-release)
will kick in and will publish your changes to npm automatically.
> fix: Doc titles include rule name

- .travis.yml
- Remove support for node v4.x (breaking change).
- Add support for node v8.x and v10.x.
> Update supported node versions

- lib/helpers/no-dupes.js
- lib/helpers/prohibit.js
- lib/rules/new-line-before-expect.js
- lib/rules/new-line-between-declarations.js
- lib/rules/no-suite-callback-args.js
- lib/rules/prefer-toBeUndefined.js
- package.json
- test/rules/named-spy.js
- test/rules/no-global-setup.js
- test/rules/no-promise-without-done-fail.js
- test/rules/no-suite-callback-args.js
- test/rules/no-unsafe-spy.js
- yarn.lock
> chore: upgrade standard to v14

- package.json
- yarn.lock
BREAKING CHANGE: upgrades eslint from v4.x to 6.x
> chore(repo): bump deps

- index.js
Fixes #300
`npm run test`
- [NA] I have updated the documentation where necessary
- [NA] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document
- [NA] I have added tests to cover my changes
> fix: Definition for rule 'jasmine/prefer-toBeUndefined' was not found

- README.md
This PR updates the documentation by adding ESLint v9 configuration while maintaining earlier ESLint configuration doc.
In a ESLint v9 project :)
Doc only.
N/A
> doc: add support for ESLint v9
