tlvince/eslint-plugin-jasmine

README.md, docs/rules/missing-expect.md, index.js, lib/rules/missing-expect.js, test/rules/missing-expect.js
This rule checks for it block which do not contain any expectations.
=> feat(missing-expect): add missing-expect rule

README.md, docs/rules/no-suite-callback-args.md, index.js, lib/rules/no-suite-callback-args.js, test/rules/no-suite-callback-args.js
Fixes #14
Seems like a low-hanging fruit :smile: 
I've never written a rule for eslint before, so this might be wrongly implemented
=> Add check for no argumetn in callback in describes

lib/prohibit.js, test/rules/no-disabled-tests.js, test/rules/no-focused-tests.js
Hi,
right now, no-focused-tests and no-disabled-tests ran on every mention of 'ddescribe', 'fdescribe' etc.
This PR makes them only run when the prohibited function is called as a function.
=> fix(no-focused-tests): only run on function calls

README.md, docs/rules/valid-expect.md, index.js, lib/rules/valid-expect.js, test/rules/valid-expect.js
The rule ensures `expect()` is called with a single argument and there is an actual expectation made.
This rule triggers a warning if `expect()` is called with more than one argument or without arguments. 
It would also issue a warning if there is nothing called on `expect()`.
=> feat(valid-expect): add valid-expect rule

README.md, docs/rules/no-unsafe-spy.md, index.js, lib/rules/no-unsafe-spy.js, test/helpers/lines_to_code.js, test/rules/no-suite-dupes.js, test/rules/no-unsafe-spy.js
no-unsafe-spy enforces spies to be defined in before/after/it blocks, see https://github.com/burabure/eslint-plugin-jasmine/blob/276894f486c953ec9ed6b9ab4bc667328ce83d78/docs/rules/no-unsafe-spy.md
=> Adds no-unsafe-spy rule

lib/rules/named-spy.js, test/rules/named-spy.js
I have jasmine.createSpy() in various ways written. When running the rule named-spy gives fatal errors because the identifier is not correctly found stopping the entire linting. This PR tries to limit the cases in which it doesn't find it.
=> Fixed multiple cases when named-spy gave errors name of undefined

lib/rules/valid-expect.js, test/rules/valid-expect.js
valid-expect gives false negatives. For example: expect(true).not.toBe(false) . this gives Matcher was not called when it should be valid. This PR solves this.
=> fix(valid-expect): members after expect are not recognized

README.md, docs/rules/no-expect-in-setup-teardown.md, index.js, lib/rules/no-expect-in-setup-teardown.js, test/rules/no-expect-in-setup-teardown.js
I don't particularly like the way I violate the DRY principle copy-pasting the `buildName` function  from the `missing-expect` rule and `setupRegexp` regular expression from the `no-global-setup` rule. We should probably have these rules import these things from a common source to avoid code duplication.
Please let me know if I should try to do this as a part of this pull request or we can do it separately.
Also let me know if you would improve/change anything else.
Note: this rule is disabled by default (I think it makes sense)..
=> feat(no-expect-in-setup-teardown): add no-expect-in-setup-teardown rule

README.md, docs/rules/new-line-between-declarations.md
Quick follow up to the new-line-between-declarations rule.
=> docs: adding new-line-between-declarations to config table

lib/rules/named-spy.js, test/rules/named-spy.js, yarn.lock
Hey,
This PR fixes a little error in the `named-spy` rule and improves the performance slightly by moving the `getIdentifier` method call after the first `if` statement.
The error happens when the spy is supposed to be used as a callback to some method or as a noop.
edit: it should close https://github.com/tlvince/eslint-plugin-jasmine/pull/67 which seems to be stale
=> fix: named spy error

lib/helpers/no-dupes.js, lib/helpers/prohibit.js, lib/rules/missing-expect.js, lib/rules/named-spy.js, lib/rules/new-line-before-expect.js, lib/rules/new-line-between-declarations.js, lib/rules/no-assign-spyon.js, lib/rules/no-describe-variables.js, lib/rules/no-expect-in-setup-teardown.js, lib/rules/no-global-setup.js, lib/rules/no-suite-callback-args.js, lib/rules/no-unsafe-spy.js, lib/rules/prefer-jasmine-matcher.js, lib/rules/valid-expect.js
To be conform with documented usage.
- http://eslint.org/docs/developer-guide/working-with-rules
Closes #132.
=> fix: update context.report() calls

docs/rules/no-global-setup.md, lib/rules/no-global-setup.js, test/rules/no-global-setup.js
Refinement to allow the inclusion of global setup blocks in situations where now root-level 'describe' suite blocks are defined (e.g. global jasmine helpers).
For full discussion, see: https://github.com/tlvince/eslint-plugin-jasmine/issues/29#issuecomment-318201806
=> fix(no-global-setup): allow global setup in helpers

lib/helpers/getLineIndentation.js, lib/helpers/getPrevTokensOnLine.js, lib/rules/new-line-before-expect.js, test/rules/new-line-before-expect.js
Currently the fix for `new-line-before-expect` will remove the indentation of the expect line.
This:
```javascript
describe("", function() {
it("", function(){
var a = 1
expect(1).toBe(1)
});
});
```
Is transformed to this:
```javascript
describe("", function() {
it("", function(){
var a = 1
expect(1).toBe(1)
});
});
```
This PR updates the behavior so that the indentation is preserved, like this:
```javascript
describe("", function() {
it("", function(){
var a = 1
expect(1).toBe(1)
});
});
```
=> fix(new-line-before-expect): maintain expectation indentation

lib/rules/new-line-between-declarations.js
Closes #156 
I tried to add a test case, for this scenario like this: 
```
{
code: linesToCode([
' describe("", function() {})',
' describe("", function)'
]),
errors: [
{
message: 'A fatal parsing error occurred: Parsing error: Unexpected token )'
}
],
output: linesToCode([
'describe("", function() {})',
'describe("", function)'
])
}
```
But the `RuleTester` throws fatal parsing error which i am not sure how to handle. Perhaps you know how I can get around that? (i looked for some docs re `RuleTester` but couldn't really find any)
Some testing in VSCode does indicate the problem is resolved by this change though...
=> fix(new-line-between-declarations): Add extra check for arguments body

docs/rules/no-promise-without-done-fail.md, lib/rules/no-promise-without-done-fail.js, test/rules/no-promise-without-done-fail.js
This updates the `no-promise-without-done-fail` rule to allow `done.fail` to be the first argument passed to a promises `then` method. This allows for test that validate the reject callback to also require the done.fail.
=> fix(rule): allow done.fail in first argument of then

README.md, docs/rules/prefer-toBeUndefined.md, index.js, lib/rules/prefer-toBeUndefined.js, test/rules/prefer-toBeUndefined.js
Add rule `prefer-toBeUndefined`, which prefers developers use the more specific `toBeUndefined()` matcher instead of the more generic `toBe(undefined)`.  (Or, optionally, to prefer the reverse.)
> _Note:_ I see the issue now with `messageIds`, there is a bug in `eslint` 4.0.0 that causes the RuleTester to fail when you use messageIds.  At some point a chore to update the version of eslint would be nice (if not to 5, then at least the latest version of 4), but for now I'll just use the `message` option directly.
- New spec added.
=> Propose rule: prefer-toBeUndefined

lib/helpers/prohibit.js, test/rules/no-focused-tests.js
Fixes issue #230.
I added a new test and ran all of them.
=> fix: Only report focused test keyword, not the whole test

README.md, docs/rules/prefer-promise-strategies.md, index.js, lib/rules/prefer-promise-strategies.js, test/rules/prefer-promise-strategies.js
This adds a new rule to enforce the use of the new `resolveTo` and `rejectWith` strategies instead of the more verbose alternative of using the `returnValue` strategy.
```js
spy.withArgs(0).returnValue(Promise.resolve(123));
spy.and.returnValue(Promise.reject(123));
```
```js
spy.withArgs(0).resolveTo(123);
spy.and.rejectWith(123);
```
The rule also includes a fixer that will transform above bad into the good example.
Aside from leading to more concise code, transforming the `returnValue(Promise.reject())` example can also avoid an unwanted UnhandledPromiseRejectionWarning.
I have added tests to cover my changes
=> Rule proposal: prefer-promise-strategies

docs/rules/new-line-before-expect.md, lib/rules/new-line-before-expect.js, test/rules/new-line-before-expect.js
This PR fixes #161. The issue is that the `new-line-before-expect` rule wasn't able to handle `await expect()` and `return expect()` properly. This is a common pattern with [jest for example](https://jestjs.io/docs/en/asynchronous#asyncawait).
I added additional unit tests for `await expect()` and `return expect()` cases.
=> fix(rule): Support await/return expect() for new-line-before-expect rule

lib/rules/new-line-before-expect.js, lib/rules/new-line-between-declarations.js, lib/rules/no-promise-without-done-fail.js
Eslint 8 requires adding a `meta.fixable` attribute to fixable rules: https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#fixes
I have added the same change on my project which couldn't be upgraded to eslint 8 because of this.
=> fix(rule): Add required meta.fixable attribute

lib/rules/no-describe-variables.js, test/rules/no-describe-variables.js
This fixes the issue #233 for arrow function definitions in describe
I wrote unit tests in Mocha for the new rules
=> fix(no-describe-variables): Check variable declarations in arrow functions

lib/rules/missing-expect.js, lib/rules/no-expect-in-setup-teardown.js, lib/rules/no-spec-dupes.js, lib/rules/no-suite-dupes.js
Eslint 9 requires that all rules that accept options implement a `meta.schema` declaration.
There are 5 rules that accept options:
```
missing-expect
no-expect-in-setup-teardown
no-spec-dupes
no-suite-dupes
prefer-toBeUndefined
```
The last one already has a `meta.schema` declaration. This change adds one for the others.
Closes #365
Manually, with an installation of eslint 9.
=> [Eslint 9] Add schema declarations

lib/rules/expect-matcher.js, lib/rules/expect-single-argument.js, lib/rules/named-spy.js, lib/rules/no-assign-spyon.js, lib/rules/no-describe-variables.js, lib/rules/no-disabled-tests.js, lib/rules/no-focused-tests.js, lib/rules/no-global-setup.js, lib/rules/no-pending-tests.js, lib/rules/no-suite-callback-args.js, lib/rules/no-unsafe-spy.js, lib/rules/prefer-jasmine-matcher.js, lib/rules/prefer-toHaveBeenCalledWith.js, lib/rules/valid-expect.js
After upgrading to eslint 9, I get the following error:
```
Oops! Something went wrong! :(
ESLint: 9.4.0
TypeError: Error while loading rule 'jasmine/no-suite-callback-args': Rule must be an object with a `create` method
```
This is because some rules directly export `create` as an anonymous function, which doesn't seem to be tolerated by eslint 9. The solution is to export an object and provide the function under a `create` property.
Manually, with an installation of eslint 9.
=> [Eslint 9] Make rules export object with a `create` method

lib/rules/missing-expect.js, lib/rules/new-line-before-expect.js, lib/rules/no-promise-without-done-fail.js, lib/rules/no-unsafe-spy.js, lib/rules/prefer-promise-strategies.js, lib/rules/prefer-toHaveBeenCalledWith.js
Eslint 9 has removed a couple of methods from the `context` object. Adapt the code to work with both the new and old eslint runtime.
More info:
https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/
Manually, with an installation of eslint 9.
=> [Eslint 9] Use new context API
